"""
Oath-4 curve definition and classical elliptic-curve arithmetic.

The Oath-4 tier is the smallest rung of the Oathbreaker Scale and is intended
to be executable end-to-end on real NISQ hardware. It exists specifically so
that the Oathbreaker architecture -- Oath-family prime-order short-Weierstrass
curve, scalar multiplication, Shor period finding, classical lattice recovery
-- can be demonstrated and verified on today's IBM Quantum devices. The Oath-4
field prime p = 11 is chosen for searchability, not Goldilocks structure; the
canonical Goldilocks prime 2^64 - 2^32 + 1 is reserved for Oath-64.

Curve: y^2 = x^3 + a*x + b  over GF(p)
  p  = 11     (4-bit field prime, Hasse interval [4, 18])
  a  = 1
  b  = 6
  n  = 13     (prime group order, no cofactor)
  G  = (2, 4) (generator of full order 13)
  k  = 12     (embedding degree; resists MOV)

Because n is prime and the group is cyclic, every affine point P on E is
expressible as P = [i]G for a unique i in 0..n-1. This isomorphism
E(F_p) ~= Z/nZ is what lets us compile the full Shor ECDLP circuit onto
a small NISQ device: the reversible group-action circuit becomes a pair of
controlled modular adders on ceil(log2(n)) = 4 qubits.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Tuple

Point = Optional[Tuple[int, int]]  # None == point at infinity

P_MOD: int = 11
A_COEF: int = 1
B_COEF: int = 6
GROUP_ORDER: int = 13
GENERATOR: Point = (2, 4)
INDEX_BITS: int = 4  # ceil(log2(13))


def ec_add(P: Point, Q: Point) -> Point:
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = P
    x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % P_MOD == 0:
            return None
        lam = (3 * x1 * x1 + A_COEF) * pow(2 * y1, -1, P_MOD) % P_MOD
    else:
        lam = (y2 - y1) * pow(x2 - x1, -1, P_MOD) % P_MOD
    x3 = (lam * lam - x1 - x2) % P_MOD
    y3 = (lam * (x1 - x3) - y1) % P_MOD
    return (x3, y3)


def ec_neg(P: Point) -> Point:
    if P is None:
        return None
    return (P[0], (-P[1]) % P_MOD)


def ec_mul(k: int, P: Point) -> Point:
    k = k % GROUP_ORDER
    R: Point = None
    Q: Point = P
    while k:
        if k & 1:
            R = ec_add(R, Q)
        Q = ec_add(Q, Q)
        k >>= 1
    return R


def point_to_index(P: Point) -> int:
    """Return i in 0..n-1 such that [i]G == P."""
    acc: Point = None
    for i in range(GROUP_ORDER):
        if acc == P:
            return i
        acc = ec_add(acc, GENERATOR)
    raise ValueError(f"{P} is not on the Oath-4 curve")


def index_to_point(i: int) -> Point:
    return ec_mul(i % GROUP_ORDER, GENERATOR)


def all_points() -> list[Point]:
    return [index_to_point(i) for i in range(GROUP_ORDER)]


@dataclass
class Instance:
    """A concrete Oath-4 ECDLP instance: given Q = [k]G, recover k."""

    k: int
    Q: Point

    @classmethod
    def from_secret(cls, k: int) -> "Instance":
        k = k % GROUP_ORDER
        if k == 0:
            raise ValueError("k=0 is a trivial instance")
        return cls(k=k, Q=ec_mul(k, GENERATOR))


def classical_dlog(Q: Point) -> int:
    """Classical discrete-log oracle for Oath-4 ground-truth verification.

    Because n = 13 is tiny, linear search is instant and foolproof -- this
    is exactly what makes Oath-4 a reliable benchmark substrate. Returns
    the unique k in 1..n-1 with [k]G = Q.
    """
    acc: Point = None
    for k in range(GROUP_ORDER):
        if acc == Q:
            return k
        acc = ec_add(acc, GENERATOR)
    raise ValueError(f"{Q} is not in the subgroup generated by G")


if __name__ == "__main__":
    print("Oath-4 curve:  y^2 = x^3 + %d*x + %d  over GF(%d)" % (A_COEF, B_COEF, P_MOD))
    print("order n = %d (prime)" % GROUP_ORDER)
    print("generator G = %s\n" % (GENERATOR,))
    print("index  point")
    for i, pt in enumerate(all_points()):
        marker = "  <-- generator" if i == 1 else ""
        print(f"  {i:2d}    {pt}{marker}")
    inst = Instance.from_secret(7)
    print(f"\nexample instance: k={inst.k}, Q={inst.Q}")
    print(f"classical dlog recovers k = {classical_dlog(inst.Q)}")
